# Generated by Django 5.0.6 on 2024-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
